image: 'php:7.1.6-cli'

stages:
  - 'Build'
  - 'QA'

build:
  stage: 'Build'
  tags:
    - 'pumpa'
  script:
    - >-
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      &&
      php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      &&
      php composer-setup.php --install-dir='.' --filename=composer
      &&
      php -r "unlink('composer-setup.php');"
      &&
      chmod +x composer
    - 'composer install'

lint:
  stage: 'QA'
  tags:
    - 'pumpa'
  script:
    - 'bin/phpcs'

phpunit:
  stage: 'QA'
  tags:
    - 'pumpa'
  variables:
    UNISH_DRUSH: '$CI_PROJECT_DIR/bin/drush'
    UNISH_DB_URL: 'sqlite://tmp/unish'
  script:
    - 'bin/phpunit'
