image: 'php:7.1.6-cli'

stages:
  - 'Build'
  - 'QA'

variables:
  COMPOSER_NO_INTERACTION: '1'
  COMPOSER_DISABLE_XDEBUG_WARN: '1'
  COMPOSER_ALLOW_SUPERUSER: '1'
  COMPOSER_CACHE_DIR: '${CI_PROJECT_DIR}/cache/composer'
  UNISH_DRUSH: '$CI_PROJECT_DIR/bin/drush'
  UNISH_DB_URL: 'sqlite://tmp/unish'

.workbench:
  tags: &tags
    - 'dockerized'

build:
  stage: 'Build'
  tags: *tags
  script:
    - >-
      curl https://getcomposer.org/download/1.4.2/composer.phar --output cache/bin/composer
      &&
      chmod +x cache/bin/composer
    - './cache/bin/composer install'

lint:
  stage: 'QA'
  tags: *tags
  script:
    - './cache/bin/composer install'
    - './bin/phpcs'

phpunit:
  stage: 'QA'
  tags: *tags
  script:
    - './cache/bin/composer install'
    - './bin/phpunit'
